version: '3.8'

services:
  r60-bot:
    image: python:3.11-slim
    container_name: r60-bot
    
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    
    environment:
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_SHEET_NAME=${GOOGLE_SHEET_NAME:-Hoja 1}
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
      - GMAIL_QUERY=${GMAIL_QUERY:-subject:R-60 has:attachment filename:xlsx is:unread}
      - NOTIFICATION_EMAIL=${NOTIFICATION_EMAIL}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MAX_EMAILS_PER_RUN=${MAX_EMAILS_PER_RUN:-10}
      - LABEL_PROCESSED=${LABEL_PROCESSED:-R60/Procesado}
      - LABEL_ERROR=${LABEL_ERROR:-R60/Error}
      - LABEL_DUPLICATE=${LABEL_DUPLICATE:-R60/Duplicado}
    
    volumes:
      - r60_source:/app-source:ro
      - r60_credentials:/app/credentials
      - r60_logs:/app/logs
      - r60_temp:/app/temp
    
    restart: unless-stopped

volumes:
  r60_source:
  r60_credentials:
  r60_logs:
  r60_temp:

networks:
  default:
    name: r60_network
