version: '3.8'

services:
  r60-bot:
    image: python:3.11-slim
    container_name: r60-bot
    working_dir: /app
    
    command: >
      sh -c "
      pip install --no-cache-dir -r requirements.txt &&
      python main.py
      "
    
    environment:
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_SHEET_NAME=${GOOGLE_SHEET_NAME:-Hoja 1}
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
      - GMAIL_QUERY=${GMAIL_QUERY:-subject:R-60 has:attachment filename:xlsx is:unread}
      - NOTIFICATION_EMAIL=${NOTIFICATION_EMAIL}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MAX_EMAILS_PER_RUN=${MAX_EMAILS_PER_RUN:-10}
      - LABEL_PROCESSED=${LABEL_PROCESSED:-R60/Procesado}
      - LABEL_ERROR=${LABEL_ERROR:-R60/Error}
      - LABEL_DUPLICATE=${LABEL_DUPLICATE:-R60/Duplicado}
    
    volumes:
      - /host_mnt/c/Users/techandi_royalchef/R-60 Bot-Test:/app
      - r60_logs:/app/logs
    
    restart: unless-stopped
    
    labels:
      - "com.portainer.stack=r60-bot"
      - "com.portainer.description=Bot de procesamiento automático de formularios R-60"

volumes:
  r60_logs:

networks:
  default:
    name: r60_network
